# PATH setup

export PATH="$HOME/.cargo/bin:$HOME/.deno/bin:$HOME/.local/share/bin:$HOME/.local/share/bin/idea/bin:$PATH"

autoload -U compinit promptinit
compinit
promptinit

# Gentoo completions
if command -v emerge &> /dev/null; then
	prompt gentoo
fi

zstyle ':completion::complete:*' use-cache 1

# Antigen plugin manager setup.
if [[ ! -a $HOME/.zsh/antigen.zsh ]]; then
	mkdir -p $HOME/.zsh
	curl -L git.io/antigen > $HOME/.zsh/antigen.zsh
fi

source $HOME/.zsh/antigen.zsh

# Attempt to load fuzzy finding in reverse search.
source /usr/share/fzf/key-bindings.zsh 2&> /dev/null
source /usr/share/doc/fzf/examples/key-bindings.zsh 2&> /dev/null

# Load the OMZ library.
antigen use oh-my-zsh

# Plugins for the prompt.
antigen bundle joshskidmore/zsh-fzf-history-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git

# Load the prompt theme.
antigen theme robbyrussell

# Apply our changes.
antigen apply

# Aliases
alias ls="exa -l"
alias la="exa -la"

# Zoxide setup
eval "$(zoxide init zsh)"

# Setup our SSH keys.
if ! pgrep -x "ssh-agent" > /dev/null; then
	eval "$(ssh-agent -s)" > /dev/null
fi

ssh-add ~/.ssh/id_ed25519 2&> /dev/null

# Make sure our $? is always successful at prompt startup.
test 1
