require "user.bootstrap"

require "user.whitespace"
require "user.treesitter"
require "user.mappings"
require "user.settings"
require "user.lualine"
require "user.accents"
require "user.theme"
require "user.tree"
require "user.git"
require "user.lsp"
